---
name: "release"

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
    inputs:
      logLevel:
        description: '日志级别'
        required: true
        default: 'warning'

jobs:
  flutter-build-windows:
    name: "Windows 版本发布"
    runs-on: "windows-latest"
    permissions: write-all
    steps:
      - name: 克隆仓库
        uses: actions/checkout@v4
      - run: |
          $tag = "${{ github.ref }}".Replace('refs/tags/', '')
          echo "tag=$(echo $tag)" >> $env:GITHUB_ENV
      - run: choco install yq

      - name: 启用 Git 长路径支持
        run: git config --system core.longpaths true

      - name: 设置 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: 设置 Java 环境
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: flutter pub get
      - run: dart pub global activate flutter_distributor
      - run: flutter_distributor release --name build_win

      - name: 上传 Windows 构建产物
        uses: actions/upload-artifact@v4
        with:
          name: windows_outputs
          path: |
            dist/*/*

  release:
    name: "发布"
    runs-on: "ubuntu-latest"
    needs: [flutter-build-windows]
    permissions: write-all
    steps:
      - name: 克隆仓库
        uses: actions/checkout@v4

      - name: 下载 Windows 构建文件
        uses: actions/download-artifact@v4
        with:
          name: windows_outputs
          path: windows_outputs

      - name: 列出 windows_outputs 目录文件
        run: ls -l windows_outputs

      - name: 创建发布版本
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            windows_outputs/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}