---
name: "发布"

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
    inputs:
      logLevel:
        description: '日志级别'
        required: true
        default: 'warning'

jobs:
  flutter-build-windows:
    name: "Windows 发布"
    runs-on: "windows-latest"
    permissions: write-all

    steps:
      - name: 克隆仓库
        uses: actions/checkout@v4
      - run: |
          $tag = "${{ github.ref }}".Replace('refs/tags/', '')
          echo "tag=$(echo $tag)" >> $env:GITHUB_ENV
      - run: echo "maple_aide_${env:tag}.zip 构建进度"
      - run: choco install yq

      - name: 启用 Git 长路径
        run: git config --system core.longpaths true

      - name: 设置 Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: 设置 Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: flutter pub get
      - run: flutter build windows
      - run: Compress-Archive build/windows/x64/runner/Release/* maple_aide_${env:tag}.zip

      - name: 上传 Windows 输出
        uses: actions/upload-artifact@v4
        with:
          name: windows_outputs
          path: |
            maple_aide_*.zip

  release:
    name: "发布"
    runs-on: "ubuntu-latest"
    needs: [flutter-build-windows]
    permissions: write-all
    steps:
      - name: 克隆仓库
        uses: actions/checkout@v4

      - name: 提取标签名称
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        shell: bash

      - name: 下载 Windows 构建文件
        uses: actions/download-artifact@v4
        with:
          name: windows_outputs
          path: windows_outputs

      - name: 列出 windows_outputs 目录中的文件
        run: ls -l windows_outputs

      - name: 将 Windows 构建文件复制到根目录
        run: cp windows_outputs/* maple_aide_${{ env.tag }}.zip