---
name: "release"

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  flutter-build-windows:
    name: "Release for windows"
    runs-on: "windows-latest"
    permissions: write-all
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - run: |
          $tag = "${{ github.ref }}".Replace('refs/tags/', '')
          echo "tag=$(echo $tag)" >> $env:GITHUB_ENV
      - run: echo "maple_aide_${env:tag}.zip build progress"
      - run: choco install yq
      - name: Enable Git longpaths
        run: git config --system core.longpaths true
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: flutter pub get
      - run: flutter build windows
      - run: Compress-Archive build/windows/x64/runner/Release/* maple_aide_${env:tag}.zip
      - name: Upload windows outputs
        uses: actions/upload-artifact@v4
        with:
          name: windows_outputs
          path: |
            maple_aide_*.zip

  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    needs: [flutter-build-windows]
    permissions: write-all
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Extract tag name
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        shell: bash


      - name: Download windows build file
        uses: actions/download-artifact@v4
        with:
          name: windows_outputs
          path: windows_outputs

      - name: List files in windows_outputs directory
        run: ls -l windows_outputs

      - name: Copy windows build file to root
        run: cp windows_outputs/* maple_aide_${{ env.tag }}.zip



      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            maple_aide_*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}